# fly.toml app configuration file generated for itehax-website on 2023-07-24T15:01:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "itehax-website"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
